<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>

  <ItemGroup Label="Analyzer">
    <PackageVersion Include="Meziantou.Analyzer" Version="3.0.203" />
    <PackageVersion Include="Roslynator.Analyzers" Version="5.0.0" />
    <PackageVersion Include="StronglyTypedId" Version="1.0.0-beta08" />
  </ItemGroup>

  <ItemGroup Label="Eigene Analyzer">
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="4.14.0" />
  </ItemGroup>

  <ItemGroup Label="Tests">
    <PackageVersion Include="xunit.v3" Version="4.0.0" />
    <PackageVersion Include="Shouldly" Version="4.3.0" />
  </ItemGroup>
</Project>
